#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: #@ data.values.app.name
  namespace: #@ data.values.app.ns
  labels:
    app: #@ data.values.app.name
spec:
  replicas: 2
  selector:
    matchLabels:
      app: #@ data.values.app.name
  template:
    metadata:
      labels:
        app: #@ data.values.app.name
    spec:
      imagePullSecrets:
      - name: harbor-creds
      containers:
      - name: #@ data.values.app.name
        image: #@ data.values.app.image
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 25
          periodSeconds: 3
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 3
        env:
        - name: MANAGEMENT_METRICS_EXPORT_WAVEFRONT_URI
          valueFrom:
            secretKeyRef:
              name: wavefront
              key: MANAGEMENT_METRICS_EXPORT_WAVEFRONT_URI
        - name: MANAGEMENT_METRICS_EXPORT_WAVEFRONT_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: wavefront
              key: MANAGEMENT_METRICS_EXPORT_WAVEFRONT_API_TOKEN
        - name: WAVEFRONT_APPLICATION_NAME
          value: #@ data.values.app.wavefront.applicationName
        - name: WAVEFRONT_APPLICATION_SERVICE
          value: #@ data.values.app.name
        - name: spring_profiles_active
          value: mysql
        - name: MYSQL_URL
          value: "jdbc:mysql://petclinic-db-mysql/petclinic"
