#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/instance: #@ data.values.app.name
  name: #@ data.values.app.name
  namespace: #@ data.values.app.ns
spec:
  rules:
  - host: #@ data.values.app.host
    http:
      paths:
      - backend:
          serviceName: 
          servicePort: http
        path: /
