#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
apiVersion: v1
kind: Secret
metadata:
  name: wavefront
  namespace: petclinic
  labels:
    app: spring-petclinic
type: Opaque
data:
  MANAGEMENT_METRICS_EXPORT_WAVEFRONT_URI: #@ base64.encode(data.values.petclinic.wavefront.uri)
  MANAGEMENT_METRICS_EXPORT_WAVEFRONT_API_TOKEN: #@ base64.encode(data.values.petclinic.wavefront.apiToken)
