#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
apiVersion: v1
kind: Service
metadata:
  name: #@ data.values.app.name
  namespace: #@ data.values.app.ns
  labels:
    app: #@ data.values.app.name
spec:
  selector:
    app: #@ data.values.app.name
  ports:
    - name: http
      protocol: TCP
      port: 8080

